version: '3.5'
services:
  notd:
    build: .
    volumes:
      - ./ServerSettings.ini:/home/steam/notd/ServerSettings.ini:ro
      - ./Saved:/home/steam/notd/LF/Saved
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
    restart: always
    tty: true
