version: '3.5'
services:
  notd:
    image: www.7v1.net/notd-server
    volumes:
      - ./Games/ServerSettings.ini:/home/steam/notd/ServerSettings.ini:ro
      - ./Games/Saved:/home/steam/notd/LF/Saved
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
    restart: always
    tty: true
